spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/prepwise_db
spring.datasource.username=postgres
spring.datasource.password=faustine831

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true